#Question1
1. Perform arithmetic operations on NumPy arrays.

In [ ]:
import numpy as np

a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
addition = a1 + a2
subtraction = a1 - a2
multiplication = a1 * a2
division = a1 / a2

print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


#Question 2
2. Write a script to compute the mean and standard deviation of a NumPy array.

In [ ]:
array = np.array([10, 20, 30, 40, 50])
mean = np.mean(array)
std_dev = np.std(array)
print("Mean:", mean)
print("Standard Deviation:", std_dev)

Mean: 30.0
Standard Deviation: 14.142135623730951


#Question 3
3. Create a NumPy array of integers from 10 to 50 with a step size of 5.


In [ ]:
array = np.arange(10, 51, 5)
print("Array:", array)

Array: [10 15 20 25 30 35 40 45 50]


#Question 4
4. Reshape the array into a 2x4 matrix.


In [ ]:
array = np.arange(10, 50, 5)
reshaped_array = array.reshape(2, 4)
print("Reshaped Array:", reshaped_array)

Reshaped Array: [[10 15 20 25]
 [30 35 40 45]]


#Question 5
5. Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):

  • Extract the sub-matrix containing the last two rows and first two columns.

  • Replace all elements greater than 4 with 0.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub_matrix = arr[1:, :2]
print("Sub-matrix:", sub_matrix)
arr[arr > 4] = 0
print("Modified Array:\n", arr)

Sub-matrix: [[4 5]
 [7 8]]
Modified Array:
 [[1 2 3]
 [4 0 0]
 [0 0 0]]


#Question 6
6. Create two 1D arrays:

   • a = np.array([1, 2, 3])

   • b = np.array([4, 5, 6])

   • Perform element-wise addition, multiplication, and division.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
add = a + b
multi = a * b
division = a / b
print("Addition:", add)
print("Multiplication:", multi)
print("Division:", division)

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


#Question 7
7. Create a random NumPy array of size (4, 4). Compute:

  • Mean of each column.

  • Maximum value of the entire array.
  
  • Sum of all elements.


In [ ]:
a = np.random.rand(4,4)
column_mean = np.mean(array, axis=0)
max_value = np.max(array)
total_sum = np.sum(array)
print("Array:", array)
print("Column Means:", column_mean)
print("Maximum Value:", max_value)
print("Total Sum:", total_sum)

Array: [10 15 20 25 30 35 40 45 50]
Column Means: 30.0
Maximum Value: 50
Total Sum: 270


#Question 8
8.Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply
the result by 2.

In [ ]:
arr = np.array([1, 2, 3, 4])
new_arr = (arr + 10) * 2
print("Modified Array:", new_arr)

Modified Array: [22 24 26 28]


#Question 9
9. Perform advanced slicing and indexing on a 3D array.

   Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from  

   1 to 100. Perform the following:

   • Extract the second "layer" (i.e., the second 2D array) in the first dimension.

   • Extract the first two rows and the last three columns from each "layer."

   • Replace all elements divisible by 3 with -1.

In [ ]:
a = np.random.randint(1, 100, (3, 4, 5))
second_layer = a[1]
print("Second Layer:", second_layer)
sliced = a[:, :2, -3:]
print("Sliced Array:", sliced)
a[a % 3 == 0] = -1
print("Modified Array:", a)

Second Layer: [[87 26 39  1 22]
 [15 13 56 21 31]
 [33 26  3 41 49]
 [24 86 94 33 15]]
Sliced Array: [[[27 74 60]
  [51 87  4]]

 [[39  1 22]
  [56 21 31]]

 [[32 65 42]
  [32 55 57]]]
Modified Array: [[[-1 38 -1 74 -1]
  [-1 -1 -1 -1  4]
  [97 -1 -1 92 53]
  [88 -1 16 11 -1]]

 [[-1 26 -1  1 22]
  [-1 13 56 -1 31]
  [-1 26 -1 41 49]
  [-1 86 94 -1 -1]]

 [[-1 97 32 65 -1]
  [95 16 32 55 -1]
  [67 40 71 71 47]
  [-1 -1 -1 67  8]]]


#Question 10
10. Work with broadcasting and advanced operations in NumPy.
  Create a NumPy array arr of shape (3, 3) with random integers between  
   
  1 and 20. Perform the following:

  • Subtract the mean of each row from its respective elements (row-wise
normalization).

  • Create a new array by squaring all the elements in arr.

  • Find the indices of the top 3 maximum values in the entire array.

In [ ]:
import numpy as np
arr = np.random.randint(1, 21, size=(3, 3))
print("Original Array:")
print(arr)
row_means = arr.mean(axis=1, keepdims=True)
normalized_arr = arr - row_means
print("\nRow-wise Normalized Array:")
print(normalized_arr)

squared_arr = np.square(arr)
print("\nSquared Array:")
print(squared_arr)

top_3_indices = np.unravel_index(np.argsort(arr.ravel())[-3:], arr.shape)
print("\nIndices of Top 3 Maximum Values:")
print(top_3_indices)


Original Array:
[[ 9 18 17]
 [ 3 19 11]
 [12 10  6]]

Row-wise Normalized Array:
[[-5.66666667  3.33333333  2.33333333]
 [-8.          8.          0.        ]
 [ 2.66666667  0.66666667 -3.33333333]]

Squared Array:
[[ 81 324 289]
 [  9 361 121]
 [144 100  36]]

Indices of Top 3 Maximum Values:
(array([0, 0, 1]), array([2, 1, 1]))
